### PR TITLE
Fixed several bugs.

### PR DESCRIPTION
**Pull request by WenzDaniel**
Hej, as already written in gitter I made a few bug fixes to our last changes. I validated that everything is working. With the new changes we added the scanner allows now the following new and old features:

0. Scanning settings for XENON1T data.
1. XENONnT data/context has become accessible. 
2. Analyzers can now register custom made plugins which are not part of straxen (yet).
3. Parameter scanner not only allows now to scan over several settings, it also allows to scan over several different run_ids. Hence it has become somewhat equivalent to submit.py
4. Some quality-of-life changes for the user. 
    * New printouts and requirement of a user input before submitting obs.
    * Added suffixes to the log, config and job file. 

Things we should still change:

1. Doc strings, so far I did not update any doc strings. Especially scan_parameters should be updated.
2. We should check the readability and usefulness of the printouts. 
3. It would be super nice if we could add a prefix to the _log, _job _config files which indicates to which setting these files belong. Might be helpful for bug fixes if 1 out of 50 job fails.

### CODE REVIEW

**Comment by WenzDaniel** [comment]
Maybe another thing, we should also allow jobs with times less than an hour.

**Comment by WenzDaniel** [comment]
Meh...., just found another issue which has to be solved first.

**Comment by WenzDaniel** [comment]
Okay fixed this issue. In the previous version it was not possible to call iterable settings which we do not want to iterate. E.g. a setting like the left and right hit extension. 

https://github.com/XENONnT/straxen/blob/32490b33a5361b3d1f4671cf1dcb92a44a396132/straxen/plugins/pulse_processing.py#L61

To fix this issue I gave now tuple-settings a special meaning. Tuples are not ripped apart by np.meshgrid any longer. All settings for which we would like to compute various combinations have to be specified as lists.

**Review by sophiafarrell — COMMENTED** [review]
You don't want to keep in the time in the log so people can see how long their job is taking? Might allow them to change the number of cpus easier (knowing where the hangup is.) Also having something end the log file once the job is done is a good check to have

**Comment by sophiafarrell** [comment]
Overall really good though thanks. I would say yes I will work on docstrings and then the check on changing the log file names to something more specific. The thing is if you run it multiple times you'll run over your old log files with the same name. but maybe we can just add an initial thing like setting0_logfilename_log etc etc

**Comment by WenzDaniel** [comment]
> 
> 
> Overall really good though thanks. I would say yes I will work on docstrings and then the check on changing the log file names to something more specific. The thing is if you run it multiple times you'll run over your old log files with the same name. but maybe we can just add an initial thing like setting0_logfilename_log etc etc

I was thinking the same. Sounds good.

**Comment by WenzDaniel** [comment]
> 
> 
> You don't want to keep in the time in the log so people can see how long their job is taking? Might allow them to change the number of cpus easier (knowing where the hangup is.) Also having something end the log file once the job is done is a good check to have

Did not notice that I took this out . Make sense to keep it.

**Pull request merged**
